[package]
name = "parsergen_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luhn3 = { version = "1.0.2" }
arrayref = "*"


parsergen_derive = { path = "../parsergen_derive" }
